### ISSUE TITLE
Fix Stop During Insertion Sort

### ISSUE THREAD

**Issue by michalkaufman** [JMCanning78/datastructures-visualization#72] opened 2020-07-01 16:24 UTC
During Insertion sort, the int stored as temp needs to be re-inserted into its correct position in the array, so specific ints in the array shift over to the right one by one to make room for it. This leads to the following issues:

1. When stop is clicked during a shift, the int being shifted which currently appears as a duplicate in the array, remains a duplicate in the array. The int stored as temp remains above the array and will disappear when another animation is started.

2. When stop is clicked at a moment when an int is shifting and one of the duplicates is in a position in between boxes, the duplicate gets stuck in that position and will stay there during any subsequent animations.

**Comment by JMCanning78** [comment] 2020-07-01 22:13
On problem 1, I'm not concerned about the `temp` variable remaining on the canvas until another animation is started.  That's desired behavior since it let's users see what the operation was doing when it was interrupted.  Taking a value out of the array and substituting a duplicate of another value, is a little troubling, but it is exactly what would happen if the insertion sort was interrupted while modifying the array.  The `temp` variable would not be restored to the array.  If someone has an easy fix to restore it, that's OK too, since it's a little easier for users to have a constant set of values in the array.  Note that if we restore the `temp` variable, we could try restoring all the array cells back to their values before the operation began.  If we did that, then we should do it for all the sorting operations and maybe shuffle too.  Doing so would make the Stop operation become Stop-and-return-to-previous-array.  And if we do that for SimpleSorting, we should probably do it for all operations in all data structures.  That could be onerous.

Problem 2 is a definite bug.  We need any temporary visualizations to be cleaned up.  The duplicate value that remains obscuring the "real" array values should be part of the call environment and get cleaned up by the next animation.

**Comment by shirasassoon** [comment] 2020-07-02 15:27
We created a branch called Issue72-stop-during-insertionsort

**Comment by JMCanning78** [comment] 2020-07-10 03:30
An example of Problem 2 above: leaving a temporary copy of an array value as it slides to the right during the shift phase of `insertionSort()`.  The problem is occurring in `assignElement()` .  In that method, a copy of the canvas items are created but never get put in the call environment for clean up if the assignment is interrupted.

I think the way to solve this is as follows.  The `callEnviron` needs to be passed from `insertionSort()` to `assignElement()` .  The copy of the canvas items in `newCell` and `newCellVal` need to added to the `callEnviron` set before calling `moveItemsTo()`.  Once they have arrived in position, the old values in the `toIndex` cell are deleted, and the `drawable` record there is updated.  After that update, `newCell` and `newCellVal` need to removed from the `callEnviron` because they are now "permanent".

**Closed** 2020-07-15 23:07 UTC
Labels: bug
